import type { NewAchievement } from '../../../db/schema';

export const ACHIEVEMENT_SEED: NewAchievement[] = [
  // ── Reading: Books Finished (tiered) ──
  {
    key: 'books_finished_1',
    groupKey: 'books_finished',
    tier: 1,
    category: 'reading',
    name: 'Ink Initiate',
    description: 'Finish your first book',
    iconName: 'book-open',
    rarity: 'common',
    threshold: 1,
    hidden: false,
    sortOrder: 1,
  },
  {
    key: 'books_finished_2',
    groupKey: 'books_finished',
    tier: 2,
    category: 'reading',
    name: 'Spine Scout',
    description: 'Finish 10 books',
    iconName: 'book-open',
    rarity: 'rare',
    threshold: 10,
    hidden: false,
    sortOrder: 2,
  },
  {
    key: 'books_finished_3',
    groupKey: 'books_finished',
    tier: 3,
    category: 'reading',
    name: 'Story Stalwart',
    description: 'Finish 35 books',
    iconName: 'book-open',
    rarity: 'epic',
    threshold: 35,
    hidden: false,
    sortOrder: 3,
  },
  {
    key: 'books_finished_4',
    groupKey: 'books_finished',
    tier: 4,
    category: 'reading',
    name: 'Grand Archivist',
    description: 'Finish 100 books',
    iconName: 'book-open',
    rarity: 'legendary',
    threshold: 100,
    hidden: false,
    sortOrder: 4,
  },

  // ── Reading: Pages Read (tiered) ──
  {
    key: 'pages_read_1',
    groupKey: 'pages_read',
    tier: 1,
    category: 'reading',
    name: 'First Leaves',
    description: 'Read 500 pages',
    iconName: 'file-text',
    rarity: 'common',
    threshold: 500,
    hidden: false,
    sortOrder: 5,
  },
  {
    key: 'pages_read_2',
    groupKey: 'pages_read',
    tier: 2,
    category: 'reading',
    name: 'Chapter Weaver',
    description: 'Read 5,000 pages',
    iconName: 'file-text',
    rarity: 'rare',
    threshold: 5000,
    hidden: false,
    sortOrder: 6,
  },
  {
    key: 'pages_read_3',
    groupKey: 'pages_read',
    tier: 3,
    category: 'reading',
    name: 'Tome Tactician',
    description: 'Read 25,000 pages',
    iconName: 'file-text',
    rarity: 'epic',
    threshold: 25000,
    hidden: false,
    sortOrder: 7,
  },
  {
    key: 'pages_read_4',
    groupKey: 'pages_read',
    tier: 4,
    category: 'reading',
    name: 'Grand Lexicon',
    description: 'Read 100,000 pages',
    iconName: 'file-text',
    rarity: 'legendary',
    threshold: 100000,
    hidden: false,
    sortOrder: 8,
  },

  // ── Reading: Hours Read (tiered) ──
  {
    key: 'hours_read_1',
    groupKey: 'hours_read',
    tier: 1,
    category: 'reading',
    name: 'Hour Initiate',
    description: 'Read for 10 hours',
    iconName: 'clock',
    rarity: 'common',
    threshold: 10,
    hidden: false,
    sortOrder: 9,
  },
  {
    key: 'hours_read_2',
    groupKey: 'hours_read',
    tier: 2,
    category: 'reading',
    name: 'Timebound Reader',
    description: 'Read for 100 hours',
    iconName: 'clock',
    rarity: 'rare',
    threshold: 100,
    hidden: false,
    sortOrder: 10,
  },
  {
    key: 'hours_read_3',
    groupKey: 'hours_read',
    tier: 3,
    category: 'reading',
    name: 'Chronicle Veteran',
    description: 'Read for 500 hours',
    iconName: 'clock',
    rarity: 'epic',
    threshold: 500,
    hidden: false,
    sortOrder: 11,
  },
  {
    key: 'hours_read_4',
    groupKey: 'hours_read',
    tier: 4,
    category: 'reading',
    name: 'Timeless Scholar',
    description: 'Read for 1,000 hours',
    iconName: 'clock',
    rarity: 'legendary',
    threshold: 1000,
    hidden: false,
    sortOrder: 12,
  },

  // ── Reading: One-offs ──
  {
    key: 'marathoner',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Marathoner',
    description: 'Complete a reading session of 90 minutes or more',
    iconName: 'timer',
    rarity: 'rare',
    threshold: 90,
    hidden: false,
    sortOrder: 13,
  },
  {
    key: 'all_nighter',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'All-nighter',
    description: 'Read between 1am and 4am',
    iconName: 'moon',
    rarity: 'epic',
    threshold: null,
    hidden: true,
    sortOrder: 14,
  },
  {
    key: 'early_bird',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Early Bird',
    description: 'Start a reading session between 5am and 7am',
    iconName: 'sunrise',
    rarity: 'rare',
    threshold: null,
    hidden: true,
    sortOrder: 15,
  },

  // ── Reading: Long Book (tiered) ──
  {
    key: 'long_book_1',
    groupKey: 'long_book',
    tier: 1,
    category: 'reading',
    name: 'Story Stretch',
    description: 'Finish a book with 300 or more pages',
    iconName: 'scroll-text',
    rarity: 'common',
    threshold: 300,
    hidden: false,
    sortOrder: 16,
  },
  {
    key: 'page_turner',
    groupKey: 'long_book',
    tier: 2,
    category: 'reading',
    name: 'Page Pathfinder',
    description: 'Finish a book with 500 or more pages',
    iconName: 'scroll-text',
    rarity: 'rare',
    threshold: 500,
    hidden: false,
    sortOrder: 17,
  },
  {
    key: 'long_book_3',
    groupKey: 'long_book',
    tier: 3,
    category: 'reading',
    name: 'Epic Voyager',
    description: 'Finish a book with 750 or more pages',
    iconName: 'book-marked',
    rarity: 'epic',
    threshold: 750,
    hidden: false,
    sortOrder: 18,
  },
  {
    key: 'tome_tamer',
    groupKey: 'long_book',
    tier: 4,
    category: 'reading',
    name: 'Tome Sovereign',
    description: 'Finish a book with 1,000 or more pages',
    iconName: 'mountain',
    rarity: 'legendary',
    threshold: 1000,
    hidden: false,
    sortOrder: 19,
  },
  {
    key: 'sprint',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Sprint',
    description: 'Finish a book in a single day',
    iconName: 'zap',
    rarity: 'epic',
    threshold: null,
    hidden: false,
    sortOrder: 20,
  },
  {
    key: 'binge_reader',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Binge Reader',
    description: 'Finish 3 or more books in a single week',
    iconName: 'fast-forward',
    rarity: 'epic',
    threshold: 3,
    hidden: false,
    sortOrder: 21,
  },

  // ── Library: Library Builder (tiered) ──
  {
    key: 'library_builder_1',
    groupKey: 'library_builder',
    tier: 1,
    category: 'library',
    name: 'Shelf Seed',
    description: 'Have 50 books in your library',
    iconName: 'library',
    rarity: 'common',
    threshold: 50,
    hidden: false,
    sortOrder: 1,
  },
  {
    key: 'library_builder_2',
    groupKey: 'library_builder',
    tier: 2,
    category: 'library',
    name: 'Collection Architect',
    description: 'Have 250 books in your library',
    iconName: 'library',
    rarity: 'rare',
    threshold: 250,
    hidden: false,
    sortOrder: 2,
  },
  {
    key: 'library_builder_3',
    groupKey: 'library_builder',
    tier: 3,
    category: 'library',
    name: 'Stack Sovereign',
    description: 'Have 1,000 books in your library',
    iconName: 'library',
    rarity: 'epic',
    threshold: 1000,
    hidden: false,
    sortOrder: 3,
  },
  {
    key: 'library_builder_4',
    groupKey: 'library_builder',
    tier: 4,
    category: 'library',
    name: 'Library of Alexandria',
    description: 'Have 5,000 books in your library',
    iconName: 'library',
    rarity: 'legendary',
    threshold: 5000,
    hidden: false,
    sortOrder: 4,
  },

  // ── Library: Annotator (tiered) ──
  {
    key: 'annotator_1',
    groupKey: 'annotator',
    tier: 1,
    category: 'library',
    name: 'Note Taker',
    description: 'Create 10 annotations',
    iconName: 'highlighter',
    rarity: 'common',
    threshold: 10,
    hidden: false,
    sortOrder: 5,
  },
  {
    key: 'annotator_2',
    groupKey: 'annotator',
    tier: 2,
    category: 'library',
    name: 'Active Annotator',
    description: 'Create 50 annotations',
    iconName: 'highlighter',
    rarity: 'rare',
    threshold: 50,
    hidden: false,
    sortOrder: 6,
  },
  {
    key: 'annotator_3',
    groupKey: 'annotator',
    tier: 3,
    category: 'library',
    name: 'Prolific Annotator',
    description: 'Create 200 annotations',
    iconName: 'highlighter',
    rarity: 'epic',
    threshold: 200,
    hidden: false,
    sortOrder: 7,
  },
  {
    key: 'annotator_4',
    groupKey: 'annotator',
    tier: 4,
    category: 'library',
    name: 'Master Annotator',
    description: 'Create 500 annotations',
    iconName: 'highlighter',
    rarity: 'legendary',
    threshold: 500,
    hidden: false,
    sortOrder: 8,
  },

  // ── Library: One-offs ──
  {
    key: 'multi_format',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Multi-Format',
    description: 'Own books in 3 or more different formats',
    iconName: 'files',
    rarity: 'rare',
    threshold: 3,
    hidden: false,
    sortOrder: 9,
  },
  {
    key: 'curator',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Curator',
    description: 'Create 10 or more collections',
    iconName: 'folder-open',
    rarity: 'rare',
    threshold: 10,
    hidden: false,
    sortOrder: 10,
  },

  // ── Exploration: Genre Explorer (tiered) ──
  {
    key: 'genre_explorer_1',
    groupKey: 'genre_explorer',
    tier: 1,
    category: 'exploration',
    name: 'Genre Curious',
    description: 'Finish books in 5 different genres',
    iconName: 'compass',
    rarity: 'common',
    threshold: 5,
    hidden: false,
    sortOrder: 1,
  },
  {
    key: 'genre_explorer_2',
    groupKey: 'genre_explorer',
    tier: 2,
    category: 'exploration',
    name: 'Genre Adventurer',
    description: 'Finish books in 10 different genres',
    iconName: 'compass',
    rarity: 'rare',
    threshold: 10,
    hidden: false,
    sortOrder: 2,
  },
  {
    key: 'genre_explorer_3',
    groupKey: 'genre_explorer',
    tier: 3,
    category: 'exploration',
    name: 'Genre Connoisseur',
    description: 'Finish books in 15 different genres',
    iconName: 'compass',
    rarity: 'epic',
    threshold: 15,
    hidden: false,
    sortOrder: 3,
  },
  {
    key: 'genre_explorer_4',
    groupKey: 'genre_explorer',
    tier: 4,
    category: 'exploration',
    name: 'Genre Master',
    description: 'Finish books in 20 different genres',
    iconName: 'compass',
    rarity: 'legendary',
    threshold: 20,
    hidden: false,
    sortOrder: 4,
  },

  // ── Exploration: Polyglot (tiered) ──
  {
    key: 'polyglot_1',
    groupKey: 'polyglot',
    tier: 1,
    category: 'exploration',
    name: 'Bilingual',
    description: 'Finish books in 2 different languages',
    iconName: 'globe',
    rarity: 'common',
    threshold: 2,
    hidden: false,
    sortOrder: 5,
  },
  {
    key: 'polyglot_2',
    groupKey: 'polyglot',
    tier: 2,
    category: 'exploration',
    name: 'Trilingual',
    description: 'Finish books in 3 different languages',
    iconName: 'globe',
    rarity: 'rare',
    threshold: 3,
    hidden: false,
    sortOrder: 6,
  },
  {
    key: 'polyglot_3',
    groupKey: 'polyglot',
    tier: 3,
    category: 'exploration',
    name: 'Multilingual',
    description: 'Finish books in 5 different languages',
    iconName: 'globe',
    rarity: 'epic',
    threshold: 5,
    hidden: false,
    sortOrder: 7,
  },
  {
    key: 'polyglot_4',
    groupKey: 'polyglot',
    tier: 4,
    category: 'exploration',
    name: 'Polyglot',
    description: 'Finish books in 7 different languages',
    iconName: 'globe',
    rarity: 'legendary',
    threshold: 7,
    hidden: false,
    sortOrder: 8,
  },

  // ── Exploration: One-offs ──
  {
    key: 'old_soul',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Old Soul',
    description: 'Finish a book published before 1900',
    iconName: 'scroll',
    rarity: 'epic',
    threshold: null,
    hidden: false,
    sortOrder: 9,
  },
  {
    key: 'new_release',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'New Release',
    description: 'Finish a book published in the current year',
    iconName: 'sparkles',
    rarity: 'rare',
    threshold: null,
    hidden: false,
    sortOrder: 10,
  },
  {
    key: 'century_span',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Century Span',
    description: 'Finish books from 3 or more different centuries',
    iconName: 'calendar-range',
    rarity: 'epic',
    threshold: 3,
    hidden: false,
    sortOrder: 11,
  },
  {
    key: 'author_deep_dive',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Author Deep Dive',
    description: 'Read 5 or more books by the same author',
    iconName: 'feather',
    rarity: 'rare',
    threshold: 5,
    hidden: false,
    sortOrder: 13,
  },

  // ── Dedication: Streak (tiered) ──
  {
    key: 'streak_1',
    groupKey: 'streak',
    tier: 1,
    category: 'dedication',
    name: 'Getting Started',
    description: 'Maintain a 7-day reading streak',
    iconName: 'flame',
    rarity: 'common',
    threshold: 7,
    hidden: false,
    sortOrder: 1,
  },
  {
    key: 'streak_2',
    groupKey: 'streak',
    tier: 2,
    category: 'dedication',
    name: 'Habitual',
    description: 'Maintain a 30-day reading streak',
    iconName: 'flame',
    rarity: 'rare',
    threshold: 30,
    hidden: false,
    sortOrder: 2,
  },
  {
    key: 'streak_3',
    groupKey: 'streak',
    tier: 3,
    category: 'dedication',
    name: 'Unstoppable',
    description: 'Maintain a 100-day reading streak',
    iconName: 'flame',
    rarity: 'epic',
    threshold: 100,
    hidden: false,
    sortOrder: 3,
  },
  {
    key: 'streak_4',
    groupKey: 'streak',
    tier: 4,
    category: 'dedication',
    name: 'Year-Long Flame',
    description: 'Maintain a 365-day reading streak',
    iconName: 'flame',
    rarity: 'legendary',
    threshold: 365,
    hidden: false,
    sortOrder: 4,
  },

  // ── Dedication: One-offs ──
  {
    key: 'year_round_reader',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Year-Round Reader',
    description: 'Read in all 12 months of a calendar year',
    iconName: 'calendar',
    rarity: 'epic',
    threshold: 12,
    hidden: false,
    sortOrder: 5,
  },
  {
    key: 'reborn',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Reborn',
    description: 'Finish a book you had abandoned for over 6 months',
    iconName: 'sprout',
    rarity: 'epic',
    threshold: null,
    hidden: true,
    sortOrder: 6,
  },
  {
    key: 'comeback_kid',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Comeback Kid',
    description: 'Resume reading after a 30-day break',
    iconName: 'corner-up-right',
    rarity: 'rare',
    threshold: 30,
    hidden: false,
    sortOrder: 7,
  },
  // ── Library: Milestone-like one-offs ──
  {
    key: 'bookmarked',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Bookmarked',
    description: 'Create your first annotation or highlight',
    iconName: 'bookmark-check',
    rarity: 'common',
    threshold: null,
    hidden: false,
    sortOrder: 13,
  },
  // ── Dedication: Calendar one-offs ──
  {
    key: 'new_year_reader',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'New Year Reader',
    description: 'Complete a reading session on January 1st',
    iconName: 'party-popper',
    rarity: 'epic',
    threshold: null,
    hidden: true,
    sortOrder: 15,
  },

  // ── Reading: Batch 2 additions ──
  {
    key: 'monthly_reader_2',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Monthly Machine',
    description: 'Finish 10 books in a single calendar month',
    iconName: 'calendar-check',
    rarity: 'legendary',
    threshold: 10,
    hidden: false,
    sortOrder: 22,
  },
  {
    key: 'slow_burn',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Slow Burn',
    description: 'Take over 90 days from start to finish a book',
    iconName: 'hourglass',
    rarity: 'rare',
    threshold: null,
    hidden: false,
    sortOrder: 23,
  },
  {
    key: 'one_sitting',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'One Sitting',
    description: 'Cover 90% or more of a book in a single reading session',
    iconName: 'coffee',
    rarity: 'epic',
    threshold: null,
    hidden: false,
    sortOrder: 24,
  },

  // ── Exploration: Batch 2 additions ──
  {
    key: 'decade_sampler',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Decade Sampler',
    description: 'Finish books published in 5 different decades',
    iconName: 'calendar-range',
    rarity: 'epic',
    threshold: 5,
    hidden: false,
    sortOrder: 14,
  },
  {
    key: 'short_story_fan',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Short Story Fan',
    description: 'Finish 5 books with fewer than 100 pages',
    iconName: 'minimize-2',
    rarity: 'rare',
    threshold: 5,
    hidden: false,
    sortOrder: 15,
  },
  {
    key: 'thick_and_thin',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Thick and Thin',
    description: 'Finish at least one book under 100 pages and one over 800 pages',
    iconName: 'arrow-up-down',
    rarity: 'rare',
    threshold: null,
    hidden: false,
    sortOrder: 16,
  },
  {
    key: 'trilogy_master',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Trilogy Master',
    description: 'Finish a complete 3-book series',
    iconName: 'list-ordered',
    rarity: 'rare',
    threshold: null,
    hidden: false,
    sortOrder: 17,
  },
  {
    key: 'genre_devotee',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Genre Devotee',
    description: 'Finish 10 books in the same genre',
    iconName: 'heart',
    rarity: 'rare',
    threshold: 10,
    hidden: false,
    sortOrder: 18,
  },

  // ── Dedication: Batch 2 additions ──
  {
    key: 'seasonal_reader',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Four Seasons',
    description: 'Read in all 4 seasons within a single year',
    iconName: 'sun',
    rarity: 'epic',
    threshold: 4,
    hidden: false,
    sortOrder: 9,
  },
  {
    key: 'perfect_month',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Perfect Month',
    description: 'Read every day of a calendar month',
    iconName: 'calendar-check',
    rarity: 'legendary',
    threshold: null,
    hidden: false,
    sortOrder: 10,
  },
  {
    key: 'consistent_reader',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Consistency Is Key',
    description: 'Read at least 30 minutes every day for 14 consecutive days',
    iconName: 'activity',
    rarity: 'rare',
    threshold: 14,
    hidden: false,
    sortOrder: 11,
  },
  {
    key: 'weekend_rhythm',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Weekend Rhythm',
    description: 'Read on 8 consecutive weekends',
    iconName: 'repeat',
    rarity: 'epic',
    threshold: 8,
    hidden: false,
    sortOrder: 12,
  },
  {
    key: 'weekend_warrior',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Weekend Warrior',
    description: 'Read for 5 or more hours in a single weekend',
    iconName: 'swords',
    rarity: 'rare',
    threshold: 5,
    hidden: false,
    sortOrder: 13,
  },
  {
    key: 'yearly_finisher_12',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Yearly Closer',
    description: 'Finish 12 books in a single calendar year',
    iconName: 'award',
    rarity: 'epic',
    threshold: 12,
    hidden: false,
    sortOrder: 14,
  },

  // ── Library: Batch 2 additions ──
  {
    key: 'note_keeper',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Note Keeper',
    description: 'Create 25 annotations that include a note',
    iconName: 'pen-line',
    rarity: 'rare',
    threshold: 25,
    hidden: false,
    sortOrder: 11,
  },
  {
    key: 'deep_dive_session',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Deep Dive',
    description: 'Create 10 annotations in a single day',
    iconName: 'highlighter',
    rarity: 'rare',
    threshold: 10,
    hidden: false,
    sortOrder: 12,
  },

  // ── Exploration: Milestone-like additions ──
  {
    key: 'first_series',
    groupKey: null,
    tier: null,
    category: 'exploration',
    name: 'Series Begun',
    description: 'Finish your first book that belongs to a named series',
    iconName: 'play',
    rarity: 'common',
    threshold: null,
    hidden: false,
    sortOrder: 19,
  },
  {
    key: 'category_sweeper',
    groupKey: null,
    tier: null,
    category: 'dedication',
    name: 'Category Sweeper',
    description: 'Earn at least one achievement in all 4 categories',
    iconName: 'trophy',
    rarity: 'legendary',
    threshold: 4,
    hidden: false,
    sortOrder: 16,
  },

  // ── Reading: Velocity ──
  {
    key: 'power_hour',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Power Hour',
    description: 'Read 75 or more pages in a single reading session',
    iconName: 'gauge',
    rarity: 'rare',
    threshold: 75,
    hidden: false,
    sortOrder: 25,
  },
  {
    key: 'speed_reader',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Speed Reader',
    description: 'Read 100 or more pages in a single day',
    iconName: 'rabbit',
    rarity: 'epic',
    threshold: 100,
    hidden: false,
    sortOrder: 26,
  },

  // ── Reading: Re-read & DNF ──
  {
    key: 'old_friend',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: 'Old Friend',
    description: 'Finish a book you were re-reading',
    iconName: 'book-heart',
    rarity: 'rare',
    threshold: null,
    hidden: false,
    sortOrder: 27,
  },
  {
    key: 'dnf_self_aware',
    groupKey: null,
    tier: null,
    category: 'reading',
    name: "It's Not You, It's Me",
    description: 'Mark a book as abandoned',
    iconName: 'book-x',
    rarity: 'common',
    threshold: null,
    hidden: true,
    sortOrder: 28,
  },

  // ── Library: Ratings ──
  {
    key: 'first_verdict',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'First Verdict',
    description: 'Rate your first book',
    iconName: 'gavel',
    rarity: 'common',
    threshold: null,
    hidden: false,
    sortOrder: 14,
  },
  {
    key: 'critic_1',
    groupKey: 'critic',
    tier: 1,
    category: 'library',
    name: 'Fledgling Critic',
    description: 'Rate 10 books',
    iconName: 'star',
    rarity: 'common',
    threshold: 10,
    hidden: false,
    sortOrder: 15,
  },
  {
    key: 'critic_2',
    groupKey: 'critic',
    tier: 2,
    category: 'library',
    name: 'Seasoned Critic',
    description: 'Rate 50 books',
    iconName: 'star',
    rarity: 'rare',
    threshold: 50,
    hidden: false,
    sortOrder: 16,
  },
  {
    key: 'critic_3',
    groupKey: 'critic',
    tier: 3,
    category: 'library',
    name: 'Esteemed Critic',
    description: 'Rate 200 books',
    iconName: 'star',
    rarity: 'epic',
    threshold: 200,
    hidden: false,
    sortOrder: 17,
  },
  {
    key: 'critic_4',
    groupKey: 'critic',
    tier: 4,
    category: 'library',
    name: 'Definitive Critic',
    description: 'Rate 500 books',
    iconName: 'star',
    rarity: 'legendary',
    threshold: 500,
    hidden: false,
    sortOrder: 18,
  },
  {
    key: 'standing_ovation',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Standing Ovation',
    description: 'Give a book a 5-star rating',
    iconName: 'medal',
    rarity: 'common',
    threshold: null,
    hidden: false,
    sortOrder: 19,
  },
  {
    key: 'across_the_board',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Across the Board',
    description: 'Use all five star ratings at least once',
    iconName: 'star-half',
    rarity: 'rare',
    threshold: 5,
    hidden: false,
    sortOrder: 20,
  },
  {
    key: 'tough_crowd',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Tough Crowd',
    description: 'Give 10 books a rating of 2 stars or lower',
    iconName: 'thumbs-down',
    rarity: 'rare',
    threshold: null,
    hidden: true,
    sortOrder: 21,
  },

  // ── Library: Annotation depth ──
  {
    key: 'wordsmith',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Wordsmith',
    description: 'Write a note longer than 280 characters',
    iconName: 'pen-tool',
    rarity: 'rare',
    threshold: 280,
    hidden: false,
    sortOrder: 22,
  },
  {
    key: 'box_of_crayons',
    groupKey: null,
    tier: null,
    category: 'library',
    name: 'Box of Crayons',
    description: 'Use all 5 highlight colors',
    iconName: 'palette',
    rarity: 'rare',
    threshold: 5,
    hidden: false,
    sortOrder: 23,
  },

  // ── Devices: Cross-device sync ──
  {
    key: 'synced_up',
    groupKey: null,
    tier: null,
    category: 'devices',
    name: 'Synced Up',
    description: 'Sync reading progress from a Kobo or KOReader device for the first time',
    iconName: 'smartphone',
    rarity: 'common',
    threshold: null,
    hidden: false,
    sortOrder: 1,
  },
  {
    key: 'full_orbit',
    groupKey: null,
    tier: null,
    category: 'devices',
    name: 'Full Orbit',
    description: 'Log reading from the web reader, a Kobo, and a KOReader device',
    iconName: 'orbit',
    rarity: 'legendary',
    threshold: 3,
    hidden: false,
    sortOrder: 2,
  },
  {
    key: 'two_worlds',
    groupKey: null,
    tier: null,
    category: 'devices',
    name: 'Two Worlds',
    description: 'Read the same book from two or more different sources',
    iconName: 'arrow-left-right',
    rarity: 'rare',
    threshold: 2,
    hidden: false,
    sortOrder: 3,
  },
];
