import {
  Activity,
  ArrowLeftRight,
  ArrowUpDown,
  Award,
  BookHeart,
  BookmarkCheck,
  BookOpen,
  BookX,
  Calendar,
  CalendarCheck,
  CalendarRange,
  Clock,
  Coffee,
  Compass,
  CornerUpRight,
  FastForward,
  Feather,
  FileText,
  Files,
  Flame,
  FolderOpen,
  Gauge,
  Gavel,
  Globe,
  Heart,
  HelpCircle,
  Highlighter,
  Hourglass,
  Library,
  ListOrdered,
  Medal,
  Minimize2,
  Moon,
  Mountain,
  Orbit,
  Palette,
  PartyPopper,
  PenLine,
  PenTool,
  Play,
  Rabbit,
  Repeat,
  Scroll,
  ScrollText,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  StarHalf,
  Sun,
  Sunrise,
  Swords,
  ThumbsDown,
  Timer,
  Trophy,
  Zap,
} from 'lucide-vue-next'
import type { Component } from 'vue'

const ICON_MAP: Record<string, Component> = {
  activity: Activity,
  'arrow-left-right': ArrowLeftRight,
  'arrow-up-down': ArrowUpDown,
  award: Award,
  'book-heart': BookHeart,
  'bookmark-check': BookmarkCheck,
  'book-open': BookOpen,
  'book-x': BookX,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-range': CalendarRange,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  'corner-up-right': CornerUpRight,
  'fast-forward': FastForward,
  feather: Feather,
  'file-text': FileText,
  files: Files,
  flame: Flame,
  'folder-open': FolderOpen,
  gauge: Gauge,
  gavel: Gavel,
  globe: Globe,
  heart: Heart,
  highlighter: Highlighter,
  hourglass: Hourglass,
  library: Library,
  'list-ordered': ListOrdered,
  medal: Medal,
  'minimize-2': Minimize2,
  moon: Moon,
  mountain: Mountain,
  orbit: Orbit,
  palette: Palette,
  'party-popper': PartyPopper,
  'pen-line': PenLine,
  'pen-tool': PenTool,
  play: Play,
  rabbit: Rabbit,
  repeat: Repeat,
  scroll: Scroll,
  'scroll-text': ScrollText,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  'star-half': StarHalf,
  sun: Sun,
  sunrise: Sunrise,
  swords: Swords,
  'thumbs-down': ThumbsDown,
  timer: Timer,
  trophy: Trophy,
  zap: Zap,
}

export function resolveLucideIcon(name: string): Component {
  return ICON_MAP[name] ?? HelpCircle
}
