import {
  Activity,
  ArrowUpDown,
  Award,
  BookmarkCheck,
  BookOpen,
  Calendar,
  CalendarCheck,
  CalendarRange,
  Clock,
  Coffee,
  Compass,
  CornerUpRight,
  FastForward,
  Feather,
  FileText,
  Files,
  Flame,
  FolderOpen,
  Globe,
  Heart,
  HelpCircle,
  Highlighter,
  Hourglass,
  Library,
  ListOrdered,
  Minimize2,
  Moon,
  Mountain,
  PartyPopper,
  PenLine,
  Play,
  Repeat,
  Scroll,
  ScrollText,
  Sparkles,
  Sprout,
  Sun,
  Sunrise,
  Swords,
  Timer,
  Trophy,
  Zap,
} from 'lucide-vue-next'
import type { Component } from 'vue'

const ICON_MAP: Record<string, Component> = {
  activity: Activity,
  'arrow-up-down': ArrowUpDown,
  award: Award,
  'bookmark-check': BookmarkCheck,
  'book-open': BookOpen,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-range': CalendarRange,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  'corner-up-right': CornerUpRight,
  'fast-forward': FastForward,
  feather: Feather,
  'file-text': FileText,
  files: Files,
  flame: Flame,
  'folder-open': FolderOpen,
  globe: Globe,
  heart: Heart,
  highlighter: Highlighter,
  hourglass: Hourglass,
  library: Library,
  'list-ordered': ListOrdered,
  'minimize-2': Minimize2,
  moon: Moon,
  mountain: Mountain,
  'party-popper': PartyPopper,
  'pen-line': PenLine,
  play: Play,
  repeat: Repeat,
  scroll: Scroll,
  'scroll-text': ScrollText,
  sparkles: Sparkles,
  sprout: Sprout,
  sun: Sun,
  sunrise: Sunrise,
  swords: Swords,
  timer: Timer,
  trophy: Trophy,
  zap: Zap,
}

export function resolveLucideIcon(name: string): Component {
  return ICON_MAP[name] ?? HelpCircle
}
